sudo: required
services:
  - docker

before_install:
  - docker build -t brianslab/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brianslab/react-test npm test

after_success:
  - docker build -t brianslab/multi-client ./client
  - docker build -t brianslab/multi-nginx ./nginx
  - docker build -t brianslab/multi-server ./server
  - docker build -t brianslab/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to dockerhub
  - docker push brianslab/multi-client
  - docker push brianslab/multi-nginx
  - docker push brianslab/multi-server
  - docker push brianslab/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-781689819986'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY